### ISSUE TITLE
Map does not display after inputting location.

### ISSUE THREAD

**Issue by pdevacc** [Daplie/pokemap-webapp#10]
Hello. Originally I  tried to follow the instruction for normal people but doubleclicking linux.pokemap.bash didn't do anything. So I followed the instructions to enter into the terminal.

This seemed to work, I navigated to https://localhost.daplie.com:3443, I input credentials (I could not find where to do the API key enter) and location and the map displayed and showed pokemon in my area. 

I went to verify that it worked correctly, clicked logout, tried to log back in, and now it sits on the screen that says "Use your real location" and with the two text boxes.  Inputting a location and clicking does nothing.

I've tried restarting everything and it still doesn't move past this screen. I've found where the key is supposed to go (I think) following Alaanor's comments. (public/static/config.js )

## Expected Behavior

The map to load like it did the first time.

## Current Behavior

Terminal outputs a really long error message. Below is a few lines from the top.

JsonWebTokenError: invalid signature
    at Object.module.exports [as verify] (/home/hplaptop/node-pokemap/node_modules/jsonwebtoken/verify.js:97:17)
    at attachSession (/home/hplaptop/node-pokemap/index.js:322:22)
    at Layer.handle [as handle_request] (/home/hplaptop/node-pokemap/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/hplaptop/node-pokemap/node_modules/express/lib/router/index.js:312:13)
    at /home/hplaptop/node-pokemap/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/hplaptop/node-pokemap/node_modules/express/lib/router/index.js:330:12)
    at next (/home/hplaptop/node-pokemap/node_modules/express/lib/router/index.js:271:10)

I looked at the localhost page and it's returning errors saying  

ignore map update - google.maps object not yet loaded map.js:301:7
ignore map update - location not set yet map.js:305:7
ignore map update - google.maps object not yet loaded map.js:301:7

on repeat.

## Possible Solution

It seems that it is not recognizing the input location. I've tried different coordinates.

## Steps to Reproduce (for problems)

1. Sorry, please see above
2.
3.
4.

## Context

Map does not load.

## Your Computer

Computer or Phone?
Computer

Windows, Mac, Linux, Android, iOS, or other?
fresh install of ubuntu 16.04 LTS

node.js v4 or v6?
v6.3.1

**Comment by pdevacc** [comment]
Using New York, NY as the location seems to work via the terminal, however, the map still does not display. The message "ignore map update - google,maps object not yet loaded" displays in the developer window.

**Comment by pdevacc** [comment]
I seem to have found a workaround -- completely wiping my browser history and restarting gets the map functional again. Not ideal, but functional.

**Comment by coolaj86** [comment]
`v1.3.5` has a workaround. I'll publish the real fix soon (See https://github.com/Daplie/node-pokemap/issues/18)
