### ISSUE TITLE
Map is Empty

### ISSUE THREAD

**Issue by aburomaissae** [Daplie/pokemap-webapp#12]
Every thing was working fine, until some hours ago, 

a while back, I opened the application (installed on my machine windows 10), all worked properly, BUT the map is empty, no pokemon, no gyms, no pokestops (I'm aware of the settings panel, as I used the application a lot lately)

**Comment by coolaj86** [comment]
Well, the official up just required a force update. I imagine it will take a few days before the people who have been decompiling the app to reverse engineer it catch up. Once they do I'll update and all will be well again.

**Comment by coolaj86** [comment]
UPDATE
=======

Please read https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

**Comment by mlfactory** [comment]
Also the scripts will not working anymore in the future?

**Comment by aburomaissae** [comment]
The scrips needs to be updated, so until its done, pokemap is not gonna work (I hope its fixed soon, doesn't make a lot of sense wonder outside to catch Rattata and Pidgey)
