### ISSUE TITLE
Dapile site wont load

### ISSUE THREAD

**Issue by ashmate19** [Daplie/pokemap-webapp#13]
## Expected Behavior
  I've followed the instructions on the site to a tee but the dapile site gives me an error.  It says The site cant be reached and it refused to connect.

## Current Behavior

This site can’t be reached

localhost.daplie.com refused to connect.
Try:
Reloading the page
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

## Steps to Reproduce (for problems)

1. followed instructions on site to install the pokemon maps but dapile site wont load after following previous instructions.
2. Not sure if it is because when i click on the windows-pokemap file it briefly opens up a small black box with some writing but then immediately closes again (I cant see what the writing says as it disappears too quick.
3.
4.

## Context

Trying to access live pokemon maps

## Your Computer

Computer or Phone?

Windows computer

Windows, Mac, Linux, Android, iOS, or other?

Windows

node.js v4 or v6?
Node.js v 6.3.1

**Comment by ashmate19** [comment]
I managed to quickly print screen the black box that was popping up when clicking to open the windows pokemaps and this is what it says.
![error](https://cloud.githubusercontent.com/assets/20841812/17407032/b8a85b1c-5a5d-11e6-9ad1-4e677f5facb5.jpg)

**Comment by coolaj86** [comment]
You have to unzip (Extract All) the folder first. You can't run programs from inside a zip folder.
