### ISSUE TITLE
Cannot Get

### ISSUE THREAD

**Issue by jgurban** [Daplie/pokemap-webapp#14]
## Expected Behavior

Safari shows Cannot Get

## Current Behavior

The error is that: Cannot Get

## Possible Solution

No clue.

## Steps to Reproduce (for problems)

1.
2.
3.
4.

## Your Computer

Computer or Phone?
Computer
Windows, Mac, Linux, Android, iOS, or other?
Mac
node.js v4 or v6?

node.js V6

**Comment by orangegringo** [comment]
same issue for me

**Comment by coolaj86** [comment]
The server didn't start.

You need to right-click on `mac-pokemap.command` and choose to open it.

**Comment by jgurban** [comment]
I did it but I got this:
throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at serve (/Users/hijgu/Downloads/pokemap-2/serve.js:24:15)
    at /Users/hijgu/Downloads/pokemap-2/serve.js:41:5
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by coolaj86** [comment]
Oh, something else on your computer is using port 3000. Try rebooting it. If that still happens then you might have a virus or something running on port 3000.

**Comment by orangegringo** [comment]
I get the same original message, "Cannot get".  But my server seems to be opening correctly in the terminal before I go into Safarie

Downloads/pokemap/mac-pok.command ; exit;
Generating 1024-bit RSA private key...
done.
Checking for existing RSA private key to secure login sessions...
RSA private key found, using it.
Listening on http://127.0.0.1:3000
Listening on https://localhost.daplie.com:3443

But then I go to Safari, type in the address, and get this:  

Cannot GET /

**Comment by baskettcase** [comment]
you can do this:

ps aux | grep node

then find the PROCESS_ID, 2nd value and then:

sudo kill -9 PROCESS_ID

That will kill the existing server if it's already running.

**Comment by orangegringo** [comment]
still having same problem.  I open the CMD file on my mac.  There is never a popup that tells me to go to the website.  

This is all I get:

Downloads/pokemap/mac-pok.command ; exit;
Generating 1024-bit RSA private key...
done.
Checking for existing RSA private key to secure login sessions...
RSA private key found, using it.
Listening on http://127.0.0.1:3000
Listening on https://localhost.daplie.com:3443


then nothing.  If I go to the website manually, I get "Cannot Get"

**Comment by coolaj86** [comment]
I fixed this. Try the latest version.
