### ISSUE TITLE
finding pokemon

### ISSUE THREAD

**Issue by baskettcase** [Daplie/pokemap-webapp#17]
I see that they got the API working again, so does this now work again? I just tried it and it wasn't finding any pokemon, so maybe it hasn't been implemented yet?

**Comment by coolaj86** [comment]
I just updated the API and published the new version.

**Comment by baskettcase** [comment]
Ok I just tested and still no pokemon, so maybe something still not working?

**Comment by HyosHi11** [comment]
Ditto on the guy above. Just installed, google maps loads fine but no pokemons shown.

**Comment by orangegringo** [comment]
same

**Comment by orangegringo** [comment]
Also, we don't say thank you enough.  THANK YOU
