### ISSUE TITLE
Ubuntu 14.04 server VM running server

### ISSUE THREAD

**Issue by chintqm03** [Daplie/pokemap-webapp#19]
## Steps to Reproduce (for problems)

1.followed all noobie steps 
2.can't execute linux-pokemap.bash

## Your Computer

Ubuntu 14.04 server VM

Linux

node.js  v6

**Comment by coolaj86** [comment]
What error message do you get?

Did you try running `bash ./linux-pokemap.bash` from inside of the folder? Or did you just double click on it?
