### ISSUE TITLE
Config file not there

### ISSUE THREAD

**Issue by KellanMcCarthy** [Daplie/pokemap-webapp#28]
node-pokemap/PokemonGo-Map-web-client/static/config.js just isn't there, and I don't know where to find it
## Expected Behavior

to find it
## Current Behavior

i couldn't find it
## Possible Solution

no
## Steps to Reproduce (for problems)

1.i 
2.don't 
3.know
4.yup

## Context

I can't add my gmaps api key
## Your Computer
custom desktop 
Computer or Phone?
computer
Windows, Mac, Linux, Android, iOS, or other?
Win10
node.js v4 or v6?
v6

**Comment by coolaj86** [comment]
The config file is there: `pokemap-webapp/static/config.js`

https://github.com/Daplie/pokemap-webapp/blob/no-server/static/config.js
