### ISSUE TITLE
Can't see a map

### ISSUE THREAD

**Issue by Zerotask** [Daplie/pokemap-webapp#4]
I set my gmaps key in the config.js and tried to login with demo / demo and a new ptc account, but I don't see a map.

![image](https://cloud.githubusercontent.com/assets/20150243/17247167/b27448bc-5591-11e6-82b4-658ead66317f.png)

**Comment by coolaj86** [comment]
Perhaps your browser is having trouble automatically acquiring your location.

Have you tried typing a location and hitting the "Use Manual Location" button?

As soon as you click either of those buttons it should show a blank map and it may take a few seconds to load.

**Comment by Zerotask** [comment]
Tried it with NYC and no map is showing.

40.7127837 -74.00594130000002
updateMap ignored - waiting for first heartbeat

**Comment by coolaj86** [comment]
Okay, I was able to reproduce the issue. I'm working on it now.

**Comment by coolaj86** [comment]
Try now. :D

**Comment by Zerotask** [comment]
Now I get this:

![image](https://cloud.githubusercontent.com/assets/20150243/17257101/c71714aa-55c0-11e6-96e5-53c0d2b59728.png)

**Comment by coolaj86** [comment]
That's showing that `updateLoc(lat, lng)` was never called - as if you never clicked the "Allow using Location" or "Set Manual Location" buttons.

Are you still trying `New York, NY` as the manual location? I tested with that and it works.

The problem you're seeing is as if no location was ever set which could only happen if:

* The Google Maps API key is invalid (but you should see an error in the console)
* You didn't click either button to update the location
* The browser is waiting forever to get a location, never timing out, never getting the location

**Comment by Zerotask** [comment]
But the demo account has default locations as I saw in the index.js.
Browser geolocation doesn't work for me (no new location) and the log says 

> Waiting for geolocation from browser
map.js:730 getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

When I enter lat and long and press on User manual location I get:

> /raw_data?latitude=49.0106028&longitude=8.400864599999977&pokemon=true&pokestops=false&gyms=true&scanned=false 500 (Internal Server Error)

**Comment by coolaj86** [comment]
Oh, if you're running straight from the package you're missing `utils/demo.json` (oversight on my part) - hence the server failure.

Try logging in with your regular account.

I'll look more into this later. There are definitely some cases I hadn't planned for.

**Comment by Zerotask** [comment]
Okay, it's working now, but I get some 404s of missing pics and I can't see scanned locations and can't deactivae Pokestops.

**Comment by coolaj86** [comment]
I haven't had time to port all of the updates from the other version, but I'd love some help.

Are you interested in fixing that functionality?

Scanned locations just requires appending to an array on each heartbeat.

Deactivating pokestops requires putting a `.filter()` on one of the arrays and checking against the config variable.

Both of these are very simple to fix on your own and I'd happily accept your pull request.
