### ISSUE TITLE
Error: Heartbeat No Result

### ISSUE THREAD

**Issue by razorrider7** [Daplie/pokemap-webapp#7]
Every time I try to update the location via the "Update Location Now" button it doesn't show any nearby pokemon. The console prints "Error: Heartbeat" and on a new line "No Result".

**Comment by razorrider7** [comment]
Nevermind. It seems to have fixed itself.

**Comment by coolaj86** [comment]
Quite often the servers just don't respond for a while. That's why the actual game crashes so often.
