### ISSUE TITLE
certificate error when starting server on debian (raspberry pi)

### ISSUE THREAD

**Issue by frickler24** [Daplie/pokemap-webapp#8]
When starting the server, I get the following error:
~/pokemap $ ./linux-pokemap.bash 

/home/knuffelpuffel/pokemap/node_modules/rsa-compat/lib/rsa-forge.js:122
    throw new Error("None of publicKeyPem, _forge, publicKeyJwk, privateKeyPem
          ^
Error: None of publicKeyPem, _forge, publicKeyJwk, privateKeyPem, or privateKeyJwk found. No way to export public key PEM
    at Object.module.exports.exportPublicPem (/home/knuffelpuffel/pokemap/node_modules/rsa-compat/lib/rsa-forge.js:122:11)
    at /home/knuffelpuffel/pokemap/serve.js:39:55
    at fs.js:272:14
    at Object.oncomplete (fs.js:107:15)

And server is stopped.

## Your Environment
* Version used: pokemap 1.3.1
* Environment name and version (e.g. Python 2.7): nodejs = v6.3.1

* Operating System and version (desktop or mobile):
debian on raspberry pi: 
Linux raspi 4.4.13+ #894 Mon Jun 13 12:43:26 BST 2016 armv6l GNU/Linux

**Comment by coolaj86** [comment]
Found the bug, Will be fixed momentarily.

**Comment by coolaj86** [comment]
It's fixed, but there is a teensy caviat since you're on raspberry pi. You need to create a private key first (it's needed to secure the login sessions).

```bash
cd pokemap/
openssl genrsa -out privkey.pem 1024
```

It will generate a key on its own if you let it go, but it'll take a long time without the module.

**Comment by coolaj86** [comment]
I actually added it to the startup script. :-D
